#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDI_APP_ICON                            1
#define ARROW_SELECT_ADD                        5
#define ARROW_SELECT_SUB                        6
#define ARROW_ADD_SUB                           7
#define IDR_TRAY_MENU                           105
#define IDD_SETTINGS                            107
#define IDD_ICON_PROPERTIES                     108
#define IDD_ABOUT                               110
#define ID_HOTKEY                               40000
#define ID_ICON_PATH                            40000
#define ID_MENU_SHOW                            40000
#define ID_WEBLINK                              40000
#define ID_FILE_BROWSE                          40001
#define ID_MENU_EXIT                            40001
#define ID_MOUSE_BUTTON                         40001
#define ID_MENU_SUSPEND                         40002
#define ID_MOUSE_CORNER                         40002
#define ID_PARAMETERS                           40002
#define ID_ICON_TITLE                           40003
#define ID_SHADER                               40003
#define ID_BROWSE_SHADER                        40004
#define ID_ICON_BROWSE                          40004
#define ID_FILE_PATH                            40005
#define ID_IMAGE                                40005
#define ID_COLOR                                40006
#define ID_TILE_IMAGE                           40007
#define ID_BROWSE_IMAGE                         40008
#define ID_BROWSE_COLOR                         40009
#define ID_GRP_ACTIVATION                       40010
#define ID_GRP_WALLPAPER                        40011
#define ID_SHADER_SPEED                         40012
#define ID_SHADER_SPEED_DISPLAY                 40013
#define ID_SCALE_IMAGE                          40014
#define ID_COLUMNS                              40015
#define ID_ROWS                                 40016
#define ID_BTN_CLEAR_SHADER                     40017
#define ID_BTN_CLEAR_IMAGE                      40018
#define ID_GRP_ICON_LAYOUT                      40019
#define ID_FONT_SIZE                            40020
#define ID_SCROLL_JUMP                          40021
#define ID_DISABLE_MAXIMIZED                    40022
